---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-app-service 
spec:
  selector:
    app: nodejs-app
  ports:
    - # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 4000
      # Port accessible outside cluster
      nodePort: 30004
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-app-deployment 
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-container 
          image: rapiddevpro/nodejs-app
          ports:
            - containerPort: 4000